# Generated by Django 2.2.22 on 2021-10-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExoMolUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('www', models.URLField(blank=True, null=True, verbose_name='website')),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('subscribed_to_newsletter', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExoMol user profile',
            },
        ),
        migrations.CreateModel(
            name='ExoMolGroupMemberProfile',
            fields=[
                ('exomoluserprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exomol_users.ExoMolUserProfile')),
                ('twitter_handle', models.CharField(blank=True, help_text='Maximum of 15 characters, omit the leading @', max_length=15, null=True)),
                ('start_date', models.DateField()),
                ('role', models.IntegerField(blank=True, choices=[(0, 'Principal Investigator'), (1, 'Project Manager'), (2, ''), (3, 'PhD student'), (4, 'MSc student')], default=2, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/profile-pics')),
                ('current', models.BooleanField(default=True)),
                ('biog', mezzanine.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ExoMol group member profile',
            },
            bases=('exomol_users.exomoluserprofile',),
        ),
    ]
