# Generated by Django 3.2.13 on 2022-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isotopologue',
            name='inchi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='isotopologue',
            name='inchikey',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='inchi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='inchikey',
            field=models.CharField(blank=True, max_length=27),
        ),
    ]
