journal_abbrevs = {
    'ACP': ('Atmos. Chem. Phys.', 'Atmospheric Chemistry and Physics'),
    'AJ': ('Astron. J.', 'Astronomical Journal'),
    'AO': ('Appl. Optics', 'Applied Optics'),
    'APB-LO': ('Appl. Phys. B-Lasers Opt.', 'Applied Physics B - Photophysics and Laser Chemistry'),
    'ApJ': ('Astrophys. J.', 'Astrophysical Journal'),
    'ApJS': ('Astrophys. J. Suppl. S.', 'Astrophysical Journal Supplement Series'),
    'AA': ('Astron. Astrophys.', 'Astronomy and Astrophysics'),
    'AAS': ('Astron. Astrophys. Sup.', 'Astronomy and Astrophysics Supplement Series'),
    'AAR': ('Astron. Astrophys. Rev.', 'Astronomy and Astrophysics Review'),
    'ASPCS': ('Astron. Soc. Pac. Conf. Ser.', 'Astronomical Society of the Pacific Conference Series'),
    'ASS': ('Astrophys. Space Sci.', 'Astrophysics and Space Science'),
    'CJC': ('Can. J. Chem.', 'Canadian Journal of Chemistry'),
    'CJP': ('Can. J. Phys.', 'Canadian Journal of Physics'),
    'CP': ('Chem. Phys.', 'Chemical Physics'),
    'CPC': ('Comput. Phys. Commun.', 'Computer Physics Communications'),
    'CPL': ('Chem. Phys. Lett.', 'Chemical Physics Letters'),
    'EPJD': ('Eur. Phys. J. D', 'European Physics Journal D'),
    'GRL': ('Geophys. Res. Lett.', 'Geophysical Resarch Letters'),
    'ICARUS': ('Icarus', 'Icarus'),
    'IJMS': ('Int. J. Mass Spectrom.', 'International Journal of Mass Spectrometry'),
    'IJQC': ('Int. J. Quantum Chem.', 'International Journal of Quantum Chemistry'),
    'JCC': ('J. Comput. Chem.', 'Journal of Computational Chemistry'),
    'JGR': ('J.  Geophys.  Res. ', 'Journal of Geophysical Research'),
    'JMS': ('J. Mol. Spectrosc.', 'Journal of Molecular Spectroscopy'),
    'JPC': ('J. Phys. Chem.', 'Journal of Physical Chemistry'),
    'JPCA': ('J. Phys. Chem. A', 'Journal of Physical Chemistry A'),
    'JPCB': ('J. Phys. Chem. B', 'Journal of Physical Chemistry B'),
    'JPCS': ('J. Phys. Conf. Ser.', ' Journal of Physics Conference Series'),
    'JCP': ('J. Chem. Phys.', 'Journal of Chemical Physics'),
    'JPB': ('J. Phys. B: At. Mol. Opt.', 'Journal of Physics B: Atomic, Molecular and Optical Physics'),
    'JOSAB': ('J. Opt. Soc. Am. B', 'Journal of the Optical Society of America B: Optical Physics'),
    'JPCRD': ('J. Phys. Chem. Ref. Data', 'Journal of Physical and Chemical Reference Data'),
    'JQSRT': ('J. Quant. Spectrosc. Radiat. Transf.', 'Journal of Quantitative Spectroscopy and Radiative Transfer'),
    'MNRAS': ('Mon. Not. R. Astron. Soc.', 'Monthly Notices of the Royal Astronomical Society'),
    'MP ': ('Mol. Phys.', 'Molecular Physics'),
    'NP': ('Nucl. Phys.', 'Nuclear Physics'),
    'NJP': ('New J. Phys', 'New Journal of Physics'),
    'OC': ('Opt. Commun.', 'Optical Communications'),
    'OL': ('Opt. Lett.', 'Optics Letters'),
    'OS': ('Opt. Spectrosc.', 'Optics and Spectroscopy'),
    'PASJ': ('Publ. Astron. Soc. Japan', 'Publications of the Astronomical Society of Japan'),
    'PASP': ('Publ. Astron. Soc. Pac.', 'Publications of the Astronomical Society of the Pacific'),
    'PCCP': ('Phys. Chem. Chem. Phys.', 'Physical Chemistry Chemical Physics'),
    'PPCF': ('Plasma Phys. Controlled Fusion', 'Plasma Physics and Controlled Fusion'),
    'PSST': ('Plasma Sources Sci. Technol.', 'Plasma Sources Science and Technology'),
    'PRA': ('Phys. Rev. A', 'Physical Review A'),
    'PRB': ('Phys. Rev. B', 'Physical Review B'),
    'PRC': ('Phys. Rev. C', 'Physical Review C'),
    'PRL': ('Phys. Rev. Lett.', 'Physical Review Letters'),
    'PR': ('Phys. Rev.', 'Physical Review'),
    'PL': ('Phys. Lett.', 'Physics Letters'),
    'PS': ('Phys. Scr.', 'Physica Scripta'),
    'PSS': ('Planet Space Sci.', 'Planetary and Space Science'),
    'QJRAS': ('Quart. J. R. Astron. Soc.', 'Quarterly Journal of the Royal Astronomical Society'),
    'SCAA': ('Spectrochim Acta A', 'Spectrochimica Acta A'),
    'SP': ('Sol. Phys.', 'Solar Physics'),
    'TCA': ('Theor. Chem. Acc.', 'Theoretical Chemistry Accounts'),
    'THEOCHEM': ('Theochem: J. Molec. Struct.', 'Theochem: Journal of Molecular Structure'),
    'ZPD': ('Z. Phys. D: Atoms Mol. Clusters', 'Zeitschrift fur Physik D: Atoms, Molecules and Clusters'),
}
