# Generated by Django 2.2.22 on 2021-10-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chem', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsecMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numin', models.FloatField()),
                ('numax', models.FloatField()),
                ('Tmin', models.FloatField()),
                ('Tmax', models.FloatField()),
                ('dnu', models.FloatField()),
                ('data_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataCollection')),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.Isotopologue')),
            ],
            options={
                'db_table': 'xsec_meta',
            },
        ),
    ]
