# Generated by Django 2.2.22 on 2021-10-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chem', '0001_initial'),
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('external', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'data_set',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type_str', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'data_type',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('local_file', models.BooleanField()),
            ],
            options={
                'db_table': 'data_link',
            },
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.BooleanField(db_column='external', default=False)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataSet')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataType')),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.Isotopologue')),
                ('link', models.ManyToManyField(db_table='data_collection__link', to='data.Link')),
                ('source', models.ManyToManyField(db_table='data_collection__source', to='refs.Source')),
            ],
            options={
                'db_table': 'data_collection',
            },
        ),
    ]
