# Generated by Django 3.2.13 on 2022-05-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0002_auto_20220430_2115'),
        ('data', '0003_dataset_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zenodo_doi', models.CharField(max_length=100)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.dataset')),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.isotopologue')),
            ],
        ),
        migrations.DeleteModel(
            name='ZenodoDOI',
        ),
    ]
