# Generated by Django 3.2.13 on 2022-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_versioning_zenodo_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
