# Generated by Django 3.2.13 on 2022-05-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_datacollection_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versioning',
            options={'ordering': ('-version',)},
        ),
    ]
