# Generated by Django 2.2.22 on 2021-10-06 10:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'source_method',
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('xsams_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'source_type',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_html', models.TextField(blank=True, null=True)),
                ('title_latex', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500, null=True)),
                ('volume', models.CharField(blank=True, max_length=10, null=True)),
                ('page_start', models.CharField(blank=True, max_length=10, null=True)),
                ('page_end', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('note_html', models.TextField(blank=True, null=True)),
                ('note_latex', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('local_file', models.CharField(blank=True, db_column='local_file', max_length=100, null=True)),
                ('article_number', models.CharField(blank=True, max_length=16, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('refID', models.CharField(blank=True, db_column='refID', max_length=100, null=True)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refs.SourceMethod')),
                ('source_type', models.ForeignKey(db_column='sourcetype_id', on_delete=django.db.models.deletion.CASCADE, to='refs.SourceType')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'source',
            },
        ),
    ]
