# Generated by Django 2.2.22 on 2021-10-06 10:09

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('headline', models.TextField()),
                ('date', models.DateField()),
                ('important', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'news items',
                'ordering': ['-date'],
            },
        ),
    ]
