# Generated by Django 2.2.22 on 2021-10-06 10:22

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('headline', models.TextField()),
                ('date', models.DateField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataSet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
