# Generated by Django 2.2.22 on 2021-10-06 10:15

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chem', '0001_initial'),
        ('data', '0001_initial'),
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectroscopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', mezzanine.core.fields.RichTextField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DataSet')),
                ('isotopologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.Isotopologue')),
                ('link', models.ManyToManyField(db_table='spectroscopic_model__link', to='data.Link')),
                ('source', models.ManyToManyField(db_table='spectroscopic_model__source', to='refs.Source')),
            ],
            options={
                'verbose_name': 'Spectroscopic Model',
                'db_table': 'spectroscopic_model',
            },
        ),
    ]
